### ISSUE TITLE
Maya plugin does not work with 2023.2

### ISSUE THREAD

**Issue by adamzeliasz1** [UnityTechnologies/URP-Defender-Character-Demo#2]
After following the installation instructions I'm getting this error:
// Error: file: C:/Program Files/Autodesk/Maya2023/scripts/others/pluginWin.mel line 316: (TressFX_Exporter)

The Plugin-Manager sees it, but it will not let me select the "Loaded" option without giving me the error above.

What version(s) of Maya work with this plugin? Thanks.

**Comment by michael430** [comment]
> After following the installation instructions I'm getting this error: // Error: file: C:/Program Files/Autodesk/Maya2023/scripts/others/pluginWin.mel line 316: (TressFX_Exporter)
> 
> The Plugin-Manager sees it, but it will not let me select the "Loaded" option without giving me the error above.
> 
> What version(s) of Maya work with this plugin? Thanks.

Updated new [plugins ](https://github.com/Unity-China/cn.unity.hairfx.core/tree/main/Maya_TressFX_Exporter~)to support new version of Maya 2022 to 2024
