### ISSUE TITLE
Errors when opening zip file in Unity 2022.2.18

### ISSUE THREAD

**Issue by adamzeliasz1** [UnityTechnologies/URP-Defender-Character-Demo#4]
Im getting these errors after using Option 2: Direct Download.

Library\PackageCache\cn.unity.hairfx.urp@bbb80d9f95\Editor\ShaderGraph\UniversalPipeline\PhysicalHair\AssetCallbacks\UniversalPhysicalHairSubTarget.cs(35,61): error CS0117: 'CorePragmas' does not contain a definition for 'ForwardSM45'
Library\PackageCache\cn.unity.hairfx.urp@bbb80d9f95\Editor\ShaderGraph\UniversalPipeline\PhysicalHair\AssetCallbacks\UniversalPhysicalHairSubTarget.cs(36,61): error CS0117: 'CorePragmas' does not contain a definition for 'InstancedSM45'
Library\PackageCache\cn.unity.hairfx.urp@bbb80d9f95\Editor\ShaderGraph\UniversalPipeline\PhysicalHair\AssetCallbacks\UniversalPhysicalHairSubTarget.cs(37,61): error CS0117: 'CorePragmas' does not contain a definition for 'DefaultSM45'

**Comment by michael430** [comment]
Already Updated, this project should work up to version 2022.3.x
